NDefines.NCountry.PS_IMPROVE_PROVINCE_BASE = 25
NDefines.NDiplomacy.DISHONORABLE_PEACE_MONTHS = 0
--NDefines.NCountry.LAND_FORCELIMIT_EXTRA_COST_FACTOR = 2.5
--NDefines.NCountry.NAVAL_FORCELIMIT_EXTRA_COST_FACTOR = 2.5
--NDefines.RAZE_PROVINCE_POWER_PER_DEVELOPMENT = 20